title: Rohan Kumar Blog
email: roku@bu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog! Here you'll find a glimpse into my life as a husband, father, and data scientist (in that order).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rohankumar-1.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_link: #
github_link:  https://github.com/rohankumar-1
linkedin_link: https://www.linkedin.com/in/rohan-kumar-in/
buymeacoffee_link: #

# Build settings
plugins:
  - jekyll-feed
  - jekyll-toc

toc:
  min_level: 1
  max_level: 1
  ordered_list: true
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

feed:
  excerpt_only: true
  posts_limit: 500
  collections:
    - recipes

kramdown:
  hard_wrap: true

future: true


highlighter: rouge

# Google analyitics id
google_analytics:
  id: G-JW9F0B7Y2 # fill in your Google Analytics ID


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - env
    - notebooks
    - venv

collections:
  recipes:
    output: true
